### ISSUE TITLE
Module 2- Women's Reproductive Health logic broken

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#243]
When testing with sex=1 (and sex =3 and Sex2 = 1), all of the women's reproductive health questions were still displayed when they should not have been. The INTRONONCISW and INTROWH questions were not displayed.

The header Women’s Reproductive Health[SECTION 2] should also not appear for those participants. For the sex = 1 participants (and sex = 3 without correct organs), they should go directly from ACIDSUP6 to the testosterone questions

**Comment by hzhao392** [comment]
@stealthv the gender parameter is GEN not GENDER

**Comment by hzhao392** [comment]
This entire section("Women’s Reproductive Health[SECTION 2]") should only be displayed for the logic for this logic:

SEX= (01 “MALE” OR 03 “INTERSEX OR OTHER”) AND GEN= (02 “FEMALE”, 04 “TRANSGENDER FEMALE”, 05 “GENDERQUEER”, OR 06 “ADDITIONAL GENDER”)

**Comment by stealthv** [comment]
I think the problem here was caused by my using GENDER instead of GEN. This has been fixed in the latest version.

**Comment by ashreves** [comment]
@stealthv I tried this with SEX=1 and still incorrectly got the Women's Reproductive Health section.

**Comment by stealthv** [comment]
@ashreves Could you please supply the entire ‘previous results’ JSON so that I can track down why it took the wrong path?

**Comment by ashreves** [comment]
@stealthv {"firstName":"Alaina","AGE":"55","SEX":["1"]}

**Comment by ashreves** [comment]
@stealthv I just tried to test this, but was not able to get the reproduction section to render, even when I had SEX=2. I will test this when it is rendering again.

**Comment by stealthv** [comment]
@ashreves Ah, it's because there is no gender (GEN). Is that a possibility? If so I'll update the logic to skip if there is no gender.

**Comment by ashreves** [comment]
@stealthv Just got off a call with Hui. It seems that it was an issue with my computer history because I was not testing on incognito mode. I will test and get back to you.

**Comment by ashreves** [comment]
@robertsamm and I will test this next week. We will test a few different sex/gender combinations. 

Similarly, we will also test issue #280

**Comment by robertsamm** [comment]
@stealthv The entire women's health section is still being displayed for SEX=3 with incorrect sex organs. I tested with SEX=3 AND SEX2=2 and got all of the women's health section (including all questions for menstrual history, pregnancy, fertility, Hormone Medications and/or Contraceptive Devices, hormone therapy).

Tested with:
{"firstName":"Amelia","AGE":"55","SEX":["3"],"SEX2":["2"], "GEN":["4"],"WORK":["1"]}

**Comment by robertsamm** [comment]
@stealthv The logic does seem to be working correctly for SEX=1 now. When @ashreves tested with SEX=1 it skipped the women's health section and was sent straight to the testosterone section.

**Comment by stealthv** [comment]
@robertsamm I just tried this with the data you mentioned and it skipped the women's health section and went to testosterone. Please try again ensuring the browser doesn't have any cached from previous test runs.

**Comment by robertsamm** [comment]
Still having the same issue for SEX=3 and SEX2=male sex organs. I am still getting all of the women's health section.
Moving to triage.


![image](https://user-images.githubusercontent.com/67074735/110174955-f1e53f00-7dce-11eb-9f4c-1a6451781ad5.png)

**Comment by robertsamm** [comment]
@hzhao392 See issue #286. This is working correctly now for the SEX=3 and SEX2=male sex organs but now it is not working for SEX=3 and SEX2=female sex organs. It is skipping this section for SEX2=6 and 7 when it should be visible.

**Comment by hzhao392** [comment]
@robertsamm thanks. I will look at both

**Comment by danielruss** [comment]
stale ... closed
