### ISSUE TITLE
Module 2 - PAINREL7 missing "Menstrual Pain" response

### ISSUE THREAD

**Issue by robertsamm** [episphere/quest#298]
PAINREL7 is not displaying "Menstrual Pain" as a response option for for SEX=3. Should display if SEX=2 or SEX=3.

![image](https://user-images.githubusercontent.com/67074735/108883888-f726da80-75d3-11eb-8bda-5834246403bf.png)

Tested with:
{"firstName":"Amelia","AGE":"55","SEX":["3"],"SEX2":["6"], "GEN":["2"],"WORK":["1"]}
{"firstName":"Amelia","AGE":"55","SEX":["3"],"SEX2":["6"], "GEN":["3"],"WORK":["1"]}
{"firstName":"Amelia","AGE":"55","SEX":["3"],"SEX2":["2"], "GEN":["4"],"WORK":["1"]}

**Comment by stealthv** [comment]
Good catch. We missed that and are only checking for SEX=2

**Comment by stealthv** [comment]
This has been updated and should now be working when SEX = 3

**Comment by robertsamm** [comment]
Still not seeing menstrual pain response option for SEX=3.

![image](https://user-images.githubusercontent.com/67074735/110172200-c5c7bf00-7dca-11eb-888c-d919561da8d6.png)
![image](https://user-images.githubusercontent.com/67074735/110172238-d5470800-7dca-11eb-99cc-287680bc9c39.png)

Moving to triage.

**Comment by robertsamm** [comment]
I see that this is working correctly now. I reloaded the markup incorrectly. Closing.
